// 新游戏只需要在这里添加一项，并把封面放进 assets/。
// id 保持不变，方便识别上次打开的游戏。
export const games = [
  {
    id: 'royal-closet',
    title: '星愿衣橱',
    description: '换上心爱的裙装，去童话世界冒险。',
    category: 'relax',
    label: '公主换装',
    color: 'lavender',
    image: 'assets/royal-closet.jpg',
    url: 'https://leeweir.github.io/royal-closet/',
  },
  {
    id: 'cococat',
    title: '喵呜小屋',
    description: '领养一只小猫，布置你们温暖的家。',
    category: 'relax',
    label: '照顾小猫',
    color: 'peach',
    image: 'assets/cococat.jpg',
    url: 'https://leeweir.github.io/cococat/',
  },
  {
    id: 'perlica-rail',
    title: '小火车接轨',
    description: '转一转铁轨，送小火车平安到站。',
    category: 'puzzle',
    label: '铁路解谜',
    color: 'sage',
    image: 'assets/perlica-rail.jpg',
    url: 'https://leeweir.github.io/perlica-rail/',
  },
  {
    id: 'bunny-carrot-adventure',
    title: '小兔的胡萝卜探险',
    description: '帮小兔找到路线，把胡萝卜带回家。',
    category: 'puzzle',
    label: '迷宫探险',
    color: 'butter',
    image: 'assets/bunny-carrot-adventure.jpg',
    url: 'https://leeweir.github.io/bunny-carrot-adventure/',
  },
  {
    id: 'peppapig',
    title: '佩奇的完美假期',
    description: '和佩奇一起出发，发现假日里的小惊喜。',
    category: 'adventure',
    label: '假日旅行',
    color: 'pink',
    image: 'assets/peppapig.jpg',
    url: 'https://leeweir.github.io/peppapig/',
  },
  {
    id: 'cocoworld',
    title: '可可的小世界',
    description: '走进方块村落，探索自己的小世界。',
    category: 'adventure',
    label: '自由探索',
    color: 'blue',
    image: 'assets/cocoworld.jpg',
    url: 'https://leeweir.github.io/cocoworld/',
  },
  {
    id: 'cocogame',
    title: '巧克力的蛋仔城',
    description: '逛小镇、种草莓，和新朋友一起玩。',
    category: 'relax',
    label: '小镇生活',
    color: 'lavender',
    image: 'assets/cocogame.jpg',
    url: 'https://leeweir.github.io/cocogame/',
  },
];
